# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  ruby: circleci/ruby@1.0
  codecov: codecov/codecov@5

jobs:
  build: # our first job, named "build"
    docker:
      - image: cimg/ruby:3.1 # use a tailored CircleCI docker image.
    steps:
      - checkout # pull down our git code.
      - ruby/install-deps # use the ruby orb to install dependencies
      - run:
          name: Make test.sh executable
          command: chmod +x test.sh

  test:  # our next job, called "test"
    # here we set TWO docker images.
    docker:
      - image: cimg/ruby:3.1 # this is our primary docker image, where step commands run.
    environment:
      CI: "true"
      CODECOV_TOKEN: ${CODECOV_TOKEN}
    # A series of steps to run, some are similar to those in "build".
    steps:
      - checkout 
      - ruby/install-deps 
      - run:
          name: Run tests and upload coverage
          command: ./test.sh
      - codecov/upload
      - store_test_results:
          path: rspec.xml
      - store_artifacts:
          path: coverage/.last_run.json
          destination: coverage-report.json

# We use workflows to orchestrate the jobs that we declared above.
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build         # Run build first.
      - test:         # Then run test,
          requires:   # Test requires that build passes for it to run.
            - build   # Finally, run the build job.
