version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  codecov: codecov/codecov@5.3.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout 
      - ruby/install-deps
      - run:
          name: Make test.sh executable
          command: chmod +x test.sh

  test:
    docker:
      - image: cimg/ruby:3.1
    environment:
      CI: 'true'
      CODECOV_TOKEN: ${CODECOV_TOKEN}
    steps:
      - checkout 
      - ruby/install-deps 
      - run:
          name: Run tests and upload coverage
          command: ./test.sh
      - store_test_results:
          path: rspec.xml
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: coverage/coverage.json
          destination: coverage-report.json
      - store_artifacts:
          path: coverage/.last_run.json
          destination: last-run-report.json

  codecov-upload:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - codecov/upload:
          files: coverage/coverage.json,coverage/.last_run.json
          disable_search: true
          fail_on_error: true

workflows:
  version: 2
  build_and_test:     
    jobs:           
      - build        
      - test:      
          requires:  
            - build
      - codecov-upload:
          requires:
            - test
