# Where things are
source:       .
destination:  ./_site
include: ['pages']
collections:
  pages:
    output:   true
  posts:
    output:   true

#Polyglot
languages: ["en", "es", "fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
